@startuml ClassDiag
Transaction -* Customer
Transaction *-- TransactionItem
TransactionItem *- RentalItem
RentalItem *- Category

class Customer{
    #name
    #rewardPoints
    #transactions
    #<<(ostream, self)
    #addTransaction(Transaction)
}
note right
<b>Reward Points</b>
10 point for childrens or regular movie
20 points for new release
end note
class Transaction{
    #items
    #<<(ostream, self)
    #addItem(TransactionItem)
    #totalCost()
    #totalPoints()
}
class TransactionItem{
    #item
    #days
    #<<(ostream, self)
    #rentalCost()
    #rewardPoints()
}
class RentalItem {
    #name
    #category
    #<<(ostream, self)
    #pricePerNight()
}
note bottom
<b>Pricing</b>
$1.00/night for Regular
$0.75/night for Childrens
$1.50/night for New Releases
end note
enum Category{
    Regular
    Childrens
    NewRelease
}
@enduml